import type { SiteStorage } from "./storage.js";
import { copyScript, escapeHtml, promptCard, shell } from "./ui.js";

export function landingPage(sites: Awaited<ReturnType<SiteStorage["list"]>>, baseUrl: string, proEnabled = false): string {
  const prompt = `Read ${baseUrl}/agent.md and publish this project with OpenQuick. Verify the live site and return its shareable URL.`;
  const cards = sites.map(site => `<a class="site" href="/sites/${encodeURIComponent(site.slug)}/"><div class="site-top"><span class="file-icon" aria-hidden="true">↗</span><span class="tag"><span class="dot"></span>Live</span></div><h3>${escapeHtml(site.slug)}</h3><p class="path mono">/sites/${escapeHtml(site.slug)}/</p><div class="site-meta"><span>${site.fileCount} file${site.fileCount === 1 ? "" : "s"} · ${(site.totalBytes / 1024).toFixed(0)} KB</span><span>${escapeHtml(new Date(site.updatedAt).toLocaleDateString("en-US", {month: "short", day: "numeric", year: "numeric", timeZone: "UTC"}))}</span></div></a>`).join("");
  return shell("Published sites", `<section class="welcome"><p class="eyebrow">From your agent to the web</p><h1>Give your work a home.</h1><p class="lead">A website, a report, a useful little tool.<br>Publish the files. Share the link.</p>${promptCard(prompt)}<div class="help-links"><a href="/join">How publishing works</a><a href="/skill.md">Publishing workflow</a><a href="/openapi.json">API reference</a></div></section>${proEnabled ? '<section class="pro-callout"><div><h2>Some work needs a private home.</h2><p>Private static sites, approved viewers, and updates throughout your hosting term.</p></div><a class="button" href="/pro">Explore Pro ↗</a></section>' : ""}<section aria-labelledby="sites-heading"><div class="section-head"><h2 id="sites-heading">Out in the world</h2><span>${sites.length} published site${sites.length === 1 ? "" : "s"}</span></div><div class="sites">${cards || '<article class="empty"><h3>Your first site belongs here.</h3><p>Give the prompt above to your agent to publish a folder with an index.html.</p></article>'}</div></section>`, {active: "sites", pro: proEnabled, script: copyScript});
}

export function joinPage(baseUrl: string): string {
  const prompt = `Read ${baseUrl}/agent.md and follow the first-deploy workflow. Use an existing private credential if available; otherwise guide me through the browser approval. Publish my static folder, verify the current and immutable release URLs, and return the deployment receipt. Never put credentials in chat or site files.`;
  return shell("Get started", `<div class="guide"><p class="eyebrow">Publish with your agent</p><h1>A few files. A live link.</h1><p class="lead">OpenQuick hosts HTML, CSS, JavaScript, and assets. Let your agent prepare the folder and take care of publishing.</p>${promptCard(prompt)}<div class="notice"><strong>One connection, then you can publish.</strong> Today, publishing requires an approved agent credential. Your agent can use an existing connection or guide you through browser approval. Credentials stay in the agent’s private storage.</div><section class="steps" aria-label="Publishing steps"><article class="step"><span class="step-number">01 · PREPARE</span><h2>Choose the work</h2><p>Use a folder with an index.html, up to 25 MB. Export framework projects to static files before publishing.</p></article><article class="step"><span class="step-number">02 · CONNECT</span><h2>Approve your agent</h2><p>If a new connection is needed, open the approval page and enter the requester code your agent provides.</p></article><article class="step"><span class="step-number">03 · PUBLISH</span><h2>Get a shareable address</h2><p>The release is uploaded together. Updates keep your site address, and every release has its own fixed link.</p></article><article class="step"><span class="step-number">04 · VERIFY</span><h2>Check the result</h2><p>Your agent checks the live pages and assets, then gives you the links and a deployment receipt.</p></article></section><div class="resources"><a href="/agent.md">Agent guide ↗</a><a href="/skill.md">Workflow ↗</a><a href="/auth.md">Authentication ↗</a><a href="/openapi.json">API reference ↗</a><a href="/.well-known/agent.json">Discovery ↗</a><a href="/llms.txt">LLMs.txt ↗</a></div></div>`, {active: "join", script: copyScript});
}
