export function proPage(id?: string): string {
  if (id && !/^[a-f0-9]{48}$/.test(id)) return "Not found";
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="referrer" content="no-referrer"><title>OpenQuick Pro deploy</title><style>
  *{box-sizing:border-box}body{background:#f7f7ef;color:#20241b;font:16px/1.6 system-ui;margin:0}main{max-width:660px;margin:8vh auto;padding:28px}a{color:inherit}h1{font-size:44px;line-height:1.1;letter-spacing:-2px}article{background:white;border:1px solid #dce0d4;border-radius:16px;padding:28px;margin:28px 0}small{color:#58604d}button{padding:13px 18px;background:#25351a;color:white;border:0;border-radius:8px;font:inherit;cursor:pointer}button:disabled{opacity:.5;cursor:wait}code{font-size:12px;overflow-wrap:anywhere}pre{white-space:pre-wrap;overflow-wrap:anywhere;background:#eff1e9;padding:16px;font-size:12px}#error{color:#962619}#result{overflow-wrap:anywhere}.badge{padding:5px 9px;background:#eceddc;border-radius:5px;font-size:12px}
  </style></head><body><main><a href="/">← OpenQuick</a><p><span class="badge">PRIVATE PILOT · TEST FUNDS</span></p><h1>Publish a Pro release.</h1><p>One payment. One immutable page or static site, hosted at a shareable URL. Your agent prepares the content; you or another agent can pay for its deployment.</p>
  ${id ? `<article data-order="${id}"><small>ONE PRO DEPLOY</small><h2>0.01 pathUSD <small>on Tempo testnet</small></h2><p>This is a test payment with no real dollar value. Content publishes after payment is confirmed.</p><p id="status">Loading payment intent…</p><button id="pay" disabled>Connect wallet & pay</button> <button id="refresh" disabled>Check status</button><p id="error" role="alert"></p><div id="result" role="status"></div><details><summary>Payment details</summary><p>Receiving wallet: <code id="recipient"></code></p><p>Content fingerprint: <code id="fingerprint"></code></p><p>Agent payment URL: <code id="payment-url"></code></p></details></article><script type="module" src="/pro-client.js"></script>` : `<article><h2>Let your agent prepare a release</h2><p>An approved OpenQuick agent creates a payment intent with the files to publish. It returns a payment link for you or an MPP-capable agent.</p><pre>POST /api/v1/pro-deploys
Authorization: Bearer &lt;private deploy credential&gt;
Idempotency-Key: &lt;unique purchase ID&gt;
Content-Type: application/json

{"files":[{"path":"index.html","content":"&lt;base64 HTML&gt;"}]}</pre><p>Open the returned <code>checkoutUrl</code>, or have an MPP client pay <code>paymentUrl</code>. The result includes the published release and transaction receipt.</p><p>Access is limited to approved pilot accounts. Regular OpenQuick publishing is still available.</p></article>`}
  <p><a href="https://commons.diy/s/open-quick/settings/payments">OpenQuick Space wallet →</a></p><small>MPP verifies the payment. OpenQuick sets the price and publishes the release. No registration of a service price in Commons is needed. Card checkout and real-money payments are not enabled yet.</small></main></body></html>`;
}
